services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data
  # app:
  #   depends_on: 
  #     - mongo
  #   build: 
  #     context: phone-book-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - target: 3000
  #       host_ip: 127.0.0.1
  #       published: "3000"
  #       protocol: tcp
  #       mode: host



