[package]
name = "lupa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.7.0"
toml = "0.8.6"
serde = "1.0"
async-trait = "0.1.74"
futures = "0.3.29"

